stages:
  - e2e

e2e:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  cache:
    key: 
      files: 
        - package-lock.json
    paths:
      - node_modules/
      - .npm/
  stage: e2e
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm run web &
    # run Cypress tests
    - npx cypress run
